const categories = {
  "清华": [
    { name: "清华官网", url: "https://www.tsinghua.edu.cn/", desc: "" },
    { name: "INFO", url: "http://info.tsinghua.edu.cn/", desc: "" },
    { name: "网络学堂", url: "https://learn.tsinghua.edu.cn/f/login", desc: "" },
    { name: "中文选课", url: "http://zhjwxk.cic.tsinghua.edu.cn/xsxk_index.jsp", desc: "" },
    { name: "荷塘雨课堂", url: "https://pro.yuketang.cn/v2/web/index", desc: "" },
    { name: "图书馆", url: "https://lib.tsinghua.edu.cn/", desc: "" },
    { name: "教参平台", url: "https://ereserves.lib.tsinghua.edu.cn/", desc: "" },
    { name: "清华邮箱", url: "https://mails.tsinghua.edu.cn/", desc: "" },
    { name: "清华云盘", url: "https://cloud.tsinghua.edu.cn/", desc: "" },
    { name: "学生清华", url: "https://student.tsinghua.edu.cn/", desc: "" },
    { name: "清华信息化", url: "https://its.tsinghua.edu.cn/index.jsp", desc: "" },
    { name: "EESAST", url: "https://eesast.com/home", desc: "" },
    { name: "THU Services", url: "https://thu.services/", desc: "" },
    { name: "新T树洞", url: "https://new-t.github.io/", desc: "" },],
  "程序": [
    { name: "GitHub", url: "https://github.com/", desc: "" },
    { name: "StackOverflow", url: "https://stackoverflow.com/", desc: "" },
    { name: "Compiler Explorer", url: "https://godbolt.org/", desc: "" },
    { name: "Overleaf", url: "https://www.overleaf.com/", desc: "" },
    { name: "菜鸟教程", url: "https://www.runoob.com/", desc: "" },
    { name: "W3School", url: "https://www.w3school.com.cn/", desc: "" },
    { name: "FreeCode", url: "https://www.freecodecamp.org/chinese/", desc: "" },
    { name: "MSLearn", url: "https://learn.microsoft.com/zh-cn/", desc: "" },
  ],
  "文献": [
    { name: "ArXiv", url: "https://arxiv.org/", desc: "" },
    { name: "Papers With Code", url: "https://paperswithcode.com/", desc: "" },
    { name: "Z-Library", url: "https://zh.z-lib.gs/", desc: "" },
    { name: "Anna's Archive", url: "https://annas-archive.gs/", desc: "" },
    { name: "知网", url: "https://www.cnki.net/", desc: "" },
    { name: "读秀", url: "https://www.duxiu.com/", desc: "" },
    { name: "Semantic Scholar", url: "https://www.semanticscholar.org/", desc: "" },
    { name: "AI Deadlines", url: "https://aideadlin.es/", desc: "" },
  ],
  "学习": [
    { name: "OIWiki", url: "https://oi-wiki.org/", desc: "" },
    { name: "CTFWiki", url: "https://ctf-wiki.org/", desc: "" },
    { name: "CSDIY", url: "https://csdiy.wiki/", desc: "" },
    { name: "力扣", url: "https://leetcode-cn.com/", desc: "" },
    { name: "洛谷", url: "https://www.luogu.com.cn/", desc: "" },
    { name: "pwn.college", url: "https://pwn.college/", desc: "" },
    { name: "CTFAIO", url: "https://firmianay.gitbook.io/ctf-all-in-one/", desc: "" },
    { name: "HelloCTF", url: "https://hello-ctf.com/", desc: "" },
  ],
  "文档": [
    { name: "Cpp Reference", url: "https://zh.cppreference.com/w/%E9%A6%96%E9%A1%B5", desc: "" },
    { name: "Python", url: "https://docs.python.org/zh-cn/3/", desc: "" },
    { name: "NumPy", url: "https://numpy.org/doc/stable/", desc: "" },
    { name: "PyTorch", url: "https://pytorch.org/docs/stable/index.html", desc: "" },
    { name: "TensorFlow", url: "https://www.tensorflow.org/api_docs", desc: "" },
    { name: "Matplotlib", url: "https://matplotlib.org/stable/index.html", desc: "" },
    { name: "Pandas", url: "https://pandas.pydata.org/docs/", desc: "" },
    { name: "🤗", url: "https://huggingface.co/docs", desc: "" },
    { name: "Unity", url: "https://docs.unity3d.com/Manual/index.html", desc: "" },
    { name: "Godot", url: "https://docs.godotengine.org/zh-cn/", desc: "" },
  ],
  "翻译": [
    { name: "DeepL", url: "https://www.deepl.com/translator", desc: "" },
    { name: "Google 翻译", url: "https://translate.google.com/", desc: "" },
    { name: "有道翻译", url: "http://fanyi.youdao.com/", desc: "" },
    { name: "百度翻译", url: "https://fanyi.baidu.com/", desc: "" },
    { name: "微软翻译", url: "https://www.bing.com/translator", desc: "" },
  ],
  "动画": [
    { name: "哔哩哔哩", url: "https://www.bilibili.com/", desc: "" },
    { name: "动画瘋", url: "https://ani.gamer.com.tw/", desc: "" },
    { name: "Pixiv", url: "https://www.pixiv.net/", desc: "" },
    { name: "Bangumi", url: "https://bangumi.tv/", desc: "" },
    { name: "H萌新番", url: "https://xf.hmacg.cn/", desc: "" },
    { name: "YuC新番", url: "https://yuc.wiki/", desc: "" },
    { name: "天使动漫", url: "https://www.tsdm39.net/forum.php", desc: "" },
    { name: "蜜柑计划", url: "https://mikanani.me/", desc: "" },
    { name: "囧次元", url: "https://jocy.fun/", desc: "" },
    { name: "樱花动漫", url: "https://yhdm.one/", desc: "" },
    { name: "AGE动漫", url: "https://agefans.com/", desc: "" },
    { name: "CliCli", url: "https://www.clicli.cc/", desc: "" },
    { name: "Omofun", url: "https://omofun.in/", desc: "" },
  ],
  "游戏": [
    { name: "Steam", url: "https://store.steampowered.com/", desc: "" },
    { name: "Epic", url: "https://store.epicgames.com/zh-CN/", desc: "" },
    { name: "DLsite", url: "https://www.dlsite.com/index.html", desc: "" },
    { name: "SteamDB", url: "https://steamdb.info/", desc: "" },
    { name: "SteamPY", url: "https://steampy.com/", desc: "" },
    { name: "Byrut", url: "https://thebyrut.org/", desc: "" },
    { name: "3DM", url: "https://www.3dmgame.com/", desc: "" },
    { name: "雀魂麻将", url: "https://game.maj-soul.com/1/", desc: "" },
  ],
  "娱乐": [
    { name: "YouTube", url: "https://www.youtube.com/", desc: "" },
    { name: "Twitch", url: "https://www.twitch.tv/", desc: "" },
    { name: "Spotify", url: "https://open.spotify.com/", desc: "" },
    { name: "YTMusic", url: "https://music.youtube.com/", desc: "" },
    { name: "网易云", url: "https://music.163.com/", desc: "" },
    { name: "QQ音乐", url: "https://y.qq.com/", desc: "" },
  ],
  "社交": [
    { name: "百度贴吧", url: "https://tieba.baidu.com/", desc: "" },
    { name: "知乎", url: "https://www.zhihu.com/", desc: "" },
    { name: "微博", url: "https://weibo.com/", desc: "" },
    { name: "NGA", url: "https://bbs.nga.cn/", desc: "" },
    { name: "Facebook", url: "https://www.facebook.com/", desc: "" },
    { name: "X", url: "https://twitter.com/", desc: "" },
    { name: "Instagram", url: "https://www.instagram.com/", desc: "" },
    { name: "Reddit", url: "https://www.reddit.com/", desc: "" },
    { name: "Tumblr", url: "https://www.tumblr.com/", desc: "" },
    { name: "Telegram", url: "https://web.telegram.org/a/", desc: "" },
    { name: "Discord", url: "https://discord.com/channels/@me", desc: "" },
    { name: "巴哈姆特", url: "https://forum.gamer.com.tw/", desc: "" },
  ],
  "百科": [
    { name: "维基百科", url: "https://zh.wikipedia.org/wiki/Wikipedia:%E9%A6%96%E9%A1%B5", desc: "" },
    { name: "百度百科", url: "https://baike.baidu.com/", desc: "" },
    { name: "萌娘百科", url: "https://zh.moegirl.org.cn/Mainpage", desc: "" },
    { name: "BWIKI", url: "https://wiki.biligame.com/wiki/%E9%A6%96%E9%A1%B5", desc: "" },
    { name: "Fandom", url: "https://www.fandom.com/", desc: "" },
    { name: "ArchWiki", url: "https://wiki.archlinuxcn.org/wiki/%E9%A6%96%E9%A1%B5", desc: "" },
    { name: "THBWiki", url: "https://thwiki.cc/", desc: "" },
    { name: "MC百科", url: "https://www.mcmod.cn/", desc: "" },
    { name: "科服Wiki", url: "https://wiki.kjfwd.com:8443/", desc: "" },
  ],
  "邮箱": [
    { name: "Gmail", url: "https://mail.google.com/", desc: "" },
    { name: "Outlook", url: "https://outlook.live.com/", desc: "" },
    { name: "QQ邮箱", url: "https://mail.qq.com/", desc: "" },
    { name: "网易邮箱", url: "https://mail.163.com/", desc: "" },
    { name: "腾讯企业", url: "https://exmail.qq.com/", desc: "" },
  ],
  "AI": [
    { name: "🤗", url: "https://huggingface.co/", desc: "" },
    { name: "ChatGPT", url: "https://chatgpt.com/", desc: "" },
    { name: "Claude", url: "https://claude.ai/", desc: "" },
    { name: "Kimi", url: "https://kimi.moonshot.cn/", desc: "" },
    { name: "天工", url: "https://www.tiangong.cn/", desc: "" },
    { name: "秘塔", url: "https://metaso.cn/", desc: "" },
    { name: "文心", url: "https://yiyan.baidu.com/", desc: "" },
    { name: "智谱", url: "https://chatglm.cn/main/detail", desc: "" },
    { name: "通义", url: "https://tongyi.aliyun.com/qianwen/", desc: "" },
  ],
  "云盘": [
    { name: "谷歌云盘", url: "https://drive.google.com/drive/", desc: "" },
    { name: "OneDrive", url: "https://onedrive.live.com/", desc: "" },
    { name: "百度网盘", url: "https://pan.baidu.com/", desc: "" },
    { name: "阿里云盘", url: "https://www.aliyundrive.com/drive/", desc: "" },
  ],
  "地图": [
    { name: "谷歌地图", url: "https://www.google.com/maps", desc: "" },
    { name: "谷歌地球", url: "https://earth.google.com/web/", desc: "" },
    { name: "百度地图", url: "https://map.baidu.com/", desc: "" },
    { name: "高德地图", url: "https://www.amap.com/", desc: "" },
    { name: "腾讯地图", url: "https://map.qq.com/", desc: "" },
    { name: "Open Street Map", url: "https://www.openstreetmap.org/", desc: "" },
  ],
  "网络": [
    { name: "SpeedTest", url: "https://www.speedtest.net/", desc: "" },
    { name: "IP138", url: "https://www.ip138.com/", desc: "" },
    { name: "Dynadot", url: "https://www.dynadot.com/", desc: "" },
    { name: "CloudFlare", url: "https://www.cloudflare.com/zh-cn/", desc: "" },
    { name: "RackNerd", url: "https://www.racknerd.com/", desc: "" },
    { name: "腾讯云", url: "https://console.cloud.tencent.com/", desc: "" },
    { name: "Gravatar", url: "https://gravatar.com/", desc: "" },
  ],
  "软件": [
    { name: "Windows", url: "https://www.microsoft.com/zh-cn/software-download/", desc: "" },
    { name: "MSDN", url: "https://msdn.itellyou.cn/", desc: "" },
    { name: "小米ROM", url: "https://xiaomirom.com/", desc: "" },
    { name: "ArchLinux", url: "https://archlinux.org/packages/", desc: "" },
    { name: "AUR", url: "https://aur.archlinux.org/", desc: "" },
    { name: "酷安", url: "https://www.coolapk.com/", desc: "" },
    { name: "腾讯软件", url: "https://pc.qq.com/", desc: "" },
    { name: "吾爱破解", url: "https://www.52pojie.cn/", desc: "" },
    { name: "LRepacks", url: "https://lrepacks.net/", desc: "" },
  ],
  "镜像": [
    { name: "清华", url: "https://mirrors.tuna.tsinghua.edu.cn/", desc: "" },
    { name: "中科大", url: "https://mirrors.ustc.edu.cn/", desc: "" },
    { name: "上交", url: "https://mirrors.sjtug.sjtu.edu.cn/", desc: "" },
    { name: "浙大", url: "https://mirrors.zju.edu.cn/", desc: "" },
    { name: "华为", url: "https://mirrors.huaweicloud.com/", desc: "" },
    { name: "腾讯", url: "https://mirrors.cloud.tencent.com/", desc: "" },
    { name: "阿里", url: "https://mirrors.aliyun.com/", desc: "" },
  ],
  "友链": [
    { name: "此页仓库", url: "https://github.com/Panxuc/start", desc: "" },
    { name: "主页", url: "https://www.panxuc.com/", desc: "" },
    { name: "Xuc's Docs", url: "https://docs.panxuc.com/", desc: "" },
    { name: "Xuc Start", url: "https://start.panxuc.com/", desc: "" },
    { name: "XuCode", url: "https://code.panxuc.com/", desc: "" },
    { name: "数据库", url: "https://sql.panxuc.com/", desc: "" },
    { name: "统计", url: "https://analytics.panxuc.com/", desc: "" },
    { name: "asdawej", url: "https://asdawej.github.io/", desc: "" },
    { name: "ClF3", url: "https://www.clf3.org/", desc: "" },
  ]
};

// categories["全部"] = Object.values(categories).flatMap((category) => category) as { name: string; url: string; desc: string }[];

export default categories;
